version: '3.2' #docker-compose.yml
networks:
  integration:
services:
  sonarqube:
    image: sonarqube:6.7.5
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    networks:
    - integration
  jenkins:
    image: jenkins
    privileged: true
    user: root
    ports:
      - 8181:8080
      - 50000:50000
    container_name: jenkins
    networks:
    - integration
    volumes:
      - /var/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube