version: '3'
networks:
  otus-api-network:
  otus-front-network:
  otus-db-network:
services:
  otus_db:
    image: mongo:4.0
    container_name: otus_db
    restart: always
    env_file:
      - .env
    volumes:
      - ${DATA-./mongodb/mongoData/}:/data/db/
      - ${MONGO_CONF_PATH-./mongodb/mongod.conf}:/etc/mongo.conf
      - ./mongodb/otus-db-build.js:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - otus-db-network
    ports:
      - 27017:27017
    command:
      - '--auth'
      - '-f'
      - '/etc/mongo.conf'
  otus_frontend:
    container_name: otus_frontend
    image: nginx:1.12.1
    restart: always
    privileged: true
    user: root
    environment:
      - NGINX_HOST=${ENV_HOST-locahost}
      - NGINX_PORT=${ENV_PORT-80}
    command: >
      /bin/bash -c
      "envsubst < /etc/nginx/sites-available/api-domain.template > /etc/nginx/sites-enabled/api-domain.conf &&
      envsubst < /etc/nginx/sites-available/api-otus.template > /etc/nginx/sites-enabled/api-otus.conf &&
      envsubst < /etc/nginx/sites-available/assets.template > /etc/nginx/sites-enabled/assets.conf &&
      envsubst < /etc/nginx/sites-available/localhost.template > /etc/nginx/sites-enabled/localhost.conf &&
      envsubst < /etc/nginx/sites-available/otus-domain.template > /etc/nginx/sites-enabled/otus-domain.conf &&
      envsubst < /etc/nginx/sites-available/otus.template > /etc/nginx/sites-enabled/otus.conf &&
      envsubst < /etc/nginx/sites-available/studio.template > /etc/nginx/sites-enabled/studio.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - otus_backend
    volumes:
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/config/
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/etc/nginx/sites-enabled/:rw
      - ${NGINX_AVAILABLE_PATH-./nginx/sites-available}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH-./nginx/ssl}:/etc/nginx/ssl/
      - ${NGINX_HTML-./nginx/html}:/usr/share/nginx/html/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - otus-front-network
      - otus-api-network
    ports:
      - 80:80
      - 443:443
    links:
      - otus_backend
  otus_backend:
    container_name: otus_backend
    image: bitnami/wildfly:14.0.1
    restart: always
    environment:
      - WILDFLY_USERNAME=${WILDFLY_USER-admin}
      - WILDFLY_PASSWORD=${WILDFLY_PASS-rBQqsMXU}
    volumes:
      - ./wildfly/persistence:/bitnami
      - ./wildfly/config:/config
      - ./wildfly/app-entrypoint.sh:/app-entrypoint.sh
    depends_on:
      - otus_db
    privileged: true
    networks:
      - otus-api-network
      - otus-db-network
    ports:
      - 9990:9990
      - 8080:8080
      - 8787:8787
    links:
      - otus_db