version: '3'
volumes:
  dados:
networks:
  otus-api:
  otus-front:
  otus-db:
services:
  mongodb_server:
    image: mongo:3.6.2
    container_name: mongodb_server
    restart: always
    env_file:
      - .env
    volumes:
      - ${DATA-./mongodb/mongoData/}:/data/db/
      - ${MONGO_CONF_PATH-./mongodb/mongod.conf}:/etc/mongo.conf
      - ./mongodb/otus-db-build.js:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - otus-db
    ports:
      - 27017:27017
    command:
      - '--auth'
      - '-f'
      - '/etc/mongo.conf'
  nginx_server:
    container_name: nginx_server
    image: nginx:1.12.1
    restart: always
    depends_on:
      - wildfly_server
    volumes:
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/etc/nginx/sites-enabled/
      - ${NGINX_AVAILABLE_PATH-./nginx/sites-available}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH-./nginx/ssl}:/etc/nginx/ssl/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - otus-front
      - otus-api
    ports:
      - 80:80
      - 443:443
    entrypoint: nginx
    command:
      - '-g'
      - 'daemon off;'
    links:
      - wildfly_server
  wildfly_server:
    container_name: wildfly_server
    image: jboss/wildfly:9.0.1.Final
    restart: always
    environment:
      - LANG=en_US.UTF-8
    volumes:
      - ${WILDFLY_XML-./wildfly/standalone.xml}:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ${WILDFLY_CONF-./wildfly/standalone.conf}:/opt/jboss/wildfly/bin/standalone.conf #Caso esteja utilizando a plataforma Windows, comente essa linha!
    depends_on:
      - mongodb_server
    networks:
      - otus-api
      - otus-db
    ports:
      - 9990:9990
      - 8080:8080
      - 8787:8787
    links:
      - mongodb_server
