version: '3'
networks:
  linda-api:
  linda-db:
  linda-front:
services:
  linda_database:
    image: postgres:9.6
    container_name: linda_database
    restart: always
    hostname: linda_database
    env_file:
      - .env
    networks:
      - linda-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/schemas:/schemas/
  linda_front:
    container_name: linda_front
    image: nginx:1.15.5
    hostname: linda_front
    depends_on:
      - linda_server
    volumes:
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/etc/nginx/sites-enabled/
      - ${NGINX_ENABLE_PATH-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_AVAILABLE_PATH-./nginx/sites-available}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH-./nginx/ssl}:/etc/nginx/ssl/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - linda-front
      - linda-api
    privileged: true
    user: root
    ports:
      - 80:80
      - 443:443
    command:
      - 'nginx'
      - '-g'
      - 'daemon off;'
    links:
      - linda_server
  linda_server:
    container_name: linda_server
    image: bitnami/wildfly:14.0.1
    restart: always
    environment:
      - WILDFLY_USERNAME=${WILDFLY_USER-admin}
      - WILDFLY_PASSWORD=${WILDFLY_PASS-DFQ3JY1lwUxjeLgu}
    hostname: linda_server
    depends_on:
      - linda_database
    volumes:
      - ./wildfly/persistence:/bitnami
      - ./wildfly/config:/config
      - ./wildfly/postgresql:/opt/bitnami/wildfly/modules/org/postgresql:rw
    networks:
      - linda-api
      - linda-db
    ports:
      - 9999:9999
      - 8787:8787
      - 9990:9990
      - 8080:8080
    privileged: true
    user: root
    links:
      - linda_database
    env_file:
      - .env
