version: '3'
networks:
  linda-api:
  linda-db:
  linda-front:
services:
  postgres_server:
    image: postgres:9.6
    container_name: postgres_server
    restart: always
    hostname: postgres_server
    env_file:
      - .env
    networks:
      - linda-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/schemas:/schemas/
  linda_nginx:
    container_name: linda_nginx
    image: nginx:1.12.1
    hostname: linda_nginx
    depends_on:
      - wildfly_server
    volumes:
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/etc/nginx/sites-enabled/
      - ${NGINX_ENABLE_PATH-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_AVAILABLE_PATH-./nginx/sites-available}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH-./nginx/ssl}:/etc/nginx/ssl/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - linda-front
      - linda-api
    ports:
      - 80:80
      - 443:443
    entrypoint: nginx
    command:
      - '-g'
      - 'daemon off;'
    links:
      - wildfly_server
  wildfly_server:
    container_name: wildfly_server
    image: jboss/wildfly:14.0.1.Final
    hostname: wildfly_server
    environment:
      - LANG=en_US.UTF-8
    depends_on:
      - postgres_server
    volumes:
      - ${WILDFLY_XML-./wildfly/standalone.xml}:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./wildfly/postgresql:/opt/jboss/wildfly/modules/org/postgresql
      - ${WILDFLY_CONF-./wildfly/standalone.conf}:/opt/jboss/wildfly/bin/standalone.conf #Caso esteja utilizando a plataforma Windows, comente essa linha!
    networks:
      - linda-api
      - linda-db
    ports:
      - 8787:8787
      - 9990:9990
      - 9999:9999
      - 8080:8080
    links:
      - postgres_server
