version: '3'
networks:
  linda-api:
  linda-db:
  linda-front:
services:
  postgres_server:
    image: postgres:9.6
    container_name: postgres_server
    restart: always
    hostname: postgres_server
    env_file:
      - .env
    networks:
      - linda-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/schemas:/schemas/
  linda_nginx:
    container_name: linda_nginx
    image: nginx:1.12.1
    hostname: linda_nginx
    depends_on:
      - jboss_server
    volumes:
      - ${NGINX_ENABLE_PATH-./nginx/sites-enabled}:/etc/nginx/sites-enabled/
      - ${NGINX_ENABLE_PATH-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_AVAILABLE_PATH-./nginx/sites-available}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH-./nginx/ssl}:/etc/nginx/ssl/
      - ${NGINX_CONF_PATH-./nginx/nginx.conf}:/etc/nginx/nginx.conf
    networks:
      - linda-front
      - linda-api
    ports:
      - 80:80
      - 443:443
    entrypoint: nginx
    command:
      - '-g'
      - 'daemon off;'
    links:
      - jboss_server
  jboss_server:
    container_name: jboss_server
    image: otussolutions/jboss:7.1.1
    hostname: jboss_server
    # build:
    #   context: ./jboss
    #   dockerfile: Dockerfile
    # restart: always
    depends_on:
      - postgres_server
    volumes:
      - ${JBOS_XML-./jboss/standalone.xml}:/opt/jboss/jboss-as-7.1.1.Final/standalone/configuration/standalone.xml
      - ${JBOS_XML_HISTORY-./jboss/standalone_xml_history}:/opt/jboss/jboss-as-7.1.1.Final/standalone/configuration/standalone_xml_history/
        #Caso esteja utilizando a plataforma Windows, comente essa linha!
      - ${JBOS_CONF-./jboss/standalone.conf}:/opt/jboss/jboss-as-7.1.1.Final/bin/standalone.conf
    networks:
      - linda-api
      - linda-db
    ports:
      - 9990:9990
      - 9999:9999
      - 8080:8080
    links:
      - postgres_server
